# Display results

In [1]:
import pandas as pd

In [2]:
loaded_samples_essays = pd.read_pickle("Datasets/sample_essays.pkl")
print("Loaded DataFrame:")
display(loaded_samples_essays)

Loaded DataFrame:

                                               Essay
0  Technology has drastically changed the way we ...
1  Climate change poses a serious threat to the e...
2  Education plays a vital role in shaping the fu...
3  The rise of social media has influenced politi...
4  Healthcare systems need to be more accessible ...

In [3]:
loaded_gen_questions = pd.read_pickle("Datasets/generated_questions.pkl")
print("Loaded DataFrame:")
display(loaded_gen_questions)

Loaded DataFrame:

,Essay,prompt_generation_time,prompt
0,Technology has drastically changed the way we ...,1.793715,What technology has drastically changed the wa...
1,Climate change poses a serious threat to the e...,0.706179,What does climate change pose a serious threat...
2,Education plays a vital role in shaping the fu...,0.492621,What role does education play in shaping the f...
3,The rise of social media has influenced politi...,0.4808,What type of media has influenced political di...
4,Healthcare systems need to be more accessible ...,0.473739,What needs to be more accessible and equitable...

In [4]:
loaded_gen_responses = pd.read_pickle("Datasets/generated_responses.pkl")
print("Loaded DataFrame:")
display(loaded_gen_responses)

Loaded DataFrame:

,Essay,prompt_generation_time,prompt,generated_text,generation_time
0,Technology has drastically changed the way we ...,1.793715,What technology has drastically changed the wa...,a computer,10.548684
1,Climate change poses a serious threat to the e...,0.706179,What does climate change pose a serious threat...,Climate change is a serious threat to the envi...,0.859673
2,Education plays a vital role in shaping the fu...,0.492621,What role does education play in shaping the f...,Educating young people is a key part of the ed...,1.096551
3,The rise of social media has influenced politi...,0.4808,What type of media has influenced political di...,media,0.22629
4,Healthcare systems need to be more accessible ...,0.473739,What needs to be more accessible and equitable...,Citizenship and Social Security,0.369725